// Generated by direct launcher
// This file will be deleted when the app exits

import 'package:the_old_reader/services/old_reader_api.dart';
import 'package:flutter/foundation.dart' show debugPrint;

void configureProxy() {
  // Set the proxy port to the one that's actually in use
  OldReaderApi.setProxyPort(3000);
  debugPrint('Proxy configured to use port 3000');
}
